<!-- There are three types of errors in programming:
(a) Syntax Errors, (b) Runtime Errors, and (c) Logical Errors


                                    Syntax Errors
Syntax errors, also called parsing errors, occur at compile time in traditional programming languages
and at interpret time in JavaScript.

When a syntax error occurs in JavaScript, only the code contained within the same thread
as the syntax error is affected and the rest of the code in other threads gets executed
assuming nothing in them depends on the code containing the error.

Example:
<script type = "text/javascript">
    
       window.print(;
    
 </script>


                                     Runtime Errors
Runtime errors, also called exceptions, occur during execution (after compilation/interpretation).

For example, the following line causes a runtime error because here the syntax is correct, 
but at runtime, it is trying to call a method that does not exist.

<script type = "text/javascript">
   
    window.printme();
   
</script>
Exceptions also affect the thread in which they occur, 
allowing other JavaScript threads to continue normal execution.


                                    Logical Errors
Logic errors can be the most difficult type of errors to track down. 
These errors are not the result of a syntax or runtime error. 
Instead, they occur when you make a mistake in the logic that drives your script 
and you do not get the result you expected.

You cannot catch those errors, because it depends on your business requirement 
what type of logic you want to put in your program.

The try...catch...finally Statement:
You can catch programmer-generated and runtime exceptions, 
but you cannot catch JavaScript syntax errors.

<script type = "text/javascript">
   
      try {
         // Code to run
         break;
      } 
      
      catch ( e ) {
         // Code to run if an exception occurs
         break;
      }
      
      finally {
         // Code that is always executed regardless of 
         // an exception occurring
      }
   
</script>

The try block must be followed by either exactly one catch block or one finally block (or one of both).
When an exception occurs in the try block, the exception is placed in e and the catch block is executed. 
The optional finally block executes unconditionally after try/catch. -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error Handling</title>
</head>
<body>
    <!-- without exception handling -->

    <script type="text/javascript">
    // function myFunc()
    // {
    //     var a=10;
    //     alert("Value of Variable a is"+a)
    // }
    

    // with Exception Handling:
    
    // function myFunc()
    // {
    // var a=100;
    // try
    //     {
    //         alert("Value of a is :"+a)
    //     }
    // catch(e)
    //     {
    //         alert("error"+e.description);
    //     }
    //         //with finally block it executes always irrespective of try and catch blocks
    //     finally
    //         {
    //             document.write("finally block Execute irrespective of try & catch");
    //         }
    //     }

    // with throw keyword:

    // You can raise an exception in one function using a string, integer, Boolean, or an object and
    //  then you can capture that exception either in the same function as we did above, 
    //  or in another function using a try...catch block.
    
    // function myFunc() 
    // {
    // var a = 100;
    // var b = 200;
        
    //     try 
    //     {
    //         if ( b == 0 ) 
    //         {
    //             throw( "Divide by zero error." ); 
    //         } 
    //         else
    //         {
    //             var c = a / b;
    //             document.write("value of c is:" + c)
    //         }
    //     }
    //     catch ( e ) 
    //     {
    //         alert("Error: " + e );
    //     } 
    // }

    //  On Error Method:

    //  The onerror event handler was the first feature to facilitate error handling in JavaScript. 
    //  The error event is fired on the window object whenever an exception occurs on the page. 

    // The onerror event handler provides three pieces of information to identify the exact nature of the
    //  error −

    // Error message − The same message that the browser would display for the given error

    // URL − The file in which the error occurred

    // Line number− The line number in the given URL that caused the error

    // You can display extracted information in whatever way you think it is better.

    // You can use an onerror method, as shown below, to display an error message in case 
    // there is any problem in loading an image.
        
        // window.onerror = function () 
        // {
        // alert("An error occured.");
        // }

        document.onerror = function (msg, url, line) {
               alert("Message : " + msg );
               alert("url : " + url );
               alert("Line number : " + line );
        }
        



    </script>


    
    <!-- <input type="button" value="Click me" onclick="myFunc()"/>    -->
    <img src="\3_ADVANCED\images\ocean.jpg" onerror="alert('An error occured during loading the image.')"/>
</body> 
</html>